groups:
  - name: example-alerts
    rules:
      - alert: ServiceDown
        expr: up{job="service_a"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.instance }} is down"
          description: "Service {{ $labels.instance }} is down for more than 1 minute."
