services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    networks:
      - metrics-net

  service_a:
    build: ./service_a
    container_name: service_a
    ports:
      - "8080:8080"
    networks:
      - metrics-net
    depends_on:
      - service_b

  service_b:
    build: ./service_b
    container_name: service_b
    ports:
      - "8081:8081"
    networks:
      - metrics-net

networks:
  metrics-net:
    driver: bridge
