version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      --config.file=/etc/prometheus/prometheus.yml
      --web.enable-lifecycle  # 启用热重载端点
    networks:
      - metrics-net

  service_a:
    build: ./service_a
    container_name: service_a
    ports:
      - "8080:8080"
    networks:
      - metrics-net
    environment:
      - TZ=UTC

  service_b:
    build: ./service_b
    container_name: service_b
    ports:
      - "8081:8081"
    networks:
      - metrics-net
    environment:
      - TZ=UTC

networks:
  metrics-net:
    driver: bridge